CREATE TABLE ACCESS_LEVELS (
    ACCESS_LEVEL_ID     INT NOT NULL AUTO_INCREMENT,
    ACCESS_LEVEL_NAME   VARCHAR(20) NOT NULL,
    
    PRIMARY KEY (ACCESS_LEVEL_ID)
);

CREATE TABLE COMPANIES (
    COMPANY_ID          INT NOT NULL AUTO_INCREMENT,
    COMPANY_NAME        VARCHAR(100) NOT NULL,
    
    PRIMARY KEY (COMPANY_ID)
);

CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID         INT NOT NULL AUTO_INCREMENT,
    EMPLOYEE_USERNAME   VARCHAR(15) NOT NULL UNIQUE,
    EMPLOYEE_PASSWORD   VARCHAR(64) NOT NULL,
    EMPLOYEE_FIRST_NAME VARCHAR(15) NOT NULL,
    EMPLOYEE_LAST_NAME  VARCHAR(15) NOT NULL,
    EMPLOYEE_EMAIL      VARCHAR(25),
    
    ACCESS_LEVEL_ID     INT NOT NULL,
    COMPANY_ID          INT NOT NULL,
    
    FOREIGN KEY (ACCESS_LEVEL_ID) REFERENCES ACCESS_LEVELS (ACCESS_LEVEL_ID),
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANIES (COMPANY_ID),
    PRIMARY KEY (EMPLOYEE_ID)
);

CREATE OR REPLACE VIEW EMPLOYEE_COMPANY_VIEW AS
    SELECT EMPLOYEE_USERNAME, EMPLOYEE_FIRST_NAME, EMPLOYEE_LAST_NAME, EMPLOYEE_EMAIL, ACCESS_LEVEL_NAME, COMPANY_NAME
    FROM EMPLOYEES E, COMPANIES C, ACCESS_LEVELS AL
    WHERE E.COMPANY_ID = C.COMPANY_ID 
    AND E.ACCESS_LEVEL_ID = AL.ACCESS_LEVEL_ID;

INSERT INTO ACCESS_LEVELS (ACCESS_LEVEL_ID, ACCESS_LEVEL_NAME) VALUES (-1, 'test access level');

INSERT INTO COMPANIES (COMPANY_ID, COMPANY_NAME) VALUES (-1, 'test company');

INSERT INTO EMPLOYEES (EMPLOYEE_ID, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, EMPLOYEE_FIRST_NAME, EMPLOYEE_LAST_NAME, EMPLOYEE_EMAIL, ACCESS_LEVEL_ID, COMPANY_ID) VALUES (-1, 'testEmployee', '', 'testFirstName', 'testLastName', 'test@email.com', -1, -1);